---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selcuksan/nginx:v0.1.3
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selcuksan/nginx:v0.1.3
  template:
    metadata:
      labels:
        app: selcuksan/nginx:v0.1.3
    spec:
      containers:
      - name: selcuksan/nginx:v0.1.3
        image: selcuksan/nginx:v0.1.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

