---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selcuksan/flask-redis-app
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selcuksan/flask-redis-app
  template:
    metadata:
      labels:
        app: selcuksan/flask-redis-app
    spec:
      containers:
      - name: selcuksan/flask-redis-app
        image: selcuksan/flask-redis-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
