---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selcuksan/myapp
  namespace: build
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selcuksan/myapp
  template:
    metadata:
      labels:
        app: selcuksan/myapp
    spec:
      containers:
      - name: selcuksan/myapp
        image: selcuksan/myapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
