---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: third-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec: 
  project: default
  source: 
    repoURL: https://github.com/selcuksan/argocd-example.git
    targetRevision: HEAD
    path: third-app
  destination:
    server: https://kubernetes.default.svc
